  stages:
#    - build
#    - push
    - deploy

  variables:
    # Устанавливаем тэг для образа
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

#  build:
#    stage: build
#    services:
#      - docker:dind
#    image: docker:latest
#    script:
#      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#      - docker-compose build
#      - docker-compose push
#    only:
#      - develop
#
#  push:
#    stage: push
#    services:
#      - docker:dind
#    image: docker:latest
#    script:
#      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#      - docker-compose push
#    only:
#      - develop


  deploy:
    stage: deploy
    script:
      - ssh litvin_admin@95.163.229.202 "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
      - ssh litvin_admin@95.163.229.202 "docker pull $CI_REGISTRY_IMAGE/train:$CI_COMMIT_REF_SLUG"
      - ssh litvin_admin@95.163.229.202 "docker stop train || true"
      - ssh litvin_admin@95.163.229.202 "docker rm train || true"
      - ssh litvin_admin@95.163.229.202 "docker run -d --name train -p 80:5000 $CI_REGISTRY_IMAGE/train:$CI_COMMIT_REF_SLUG"
    only:
      - develop
