stages:
  - build
  - deploy


#variables:
#  DOCKER_HOST: tcp://docker:2375/
#  DOCKER_DRIVER: overlay2


#image:
#  name: docker/compose:latest
#
#services:
#  - docker:dind


build:
  stage: build
  image: docker:20
  services:
    - docker:20-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs/client"
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker-compose build
    - docker-compose push
  only:
    - develop

deploy:
  stage: deploy
  script:
    - docker-compose up
  only:
    - develop

