  stages:
#    - build
#    - push
    - deploy

  variables:
    # Устанавливаем тэг для образа
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  deploy:
    stage: deploy
    script:
      - ssh -v $SSH_USR@$SSH_ADDR "chmod +x $CI_PROJECT_NAME && rm -rf $CI_PROJECT_NAME"
      - ssh $SSH_USR@$SSH_ADDR "git clone --depth 1 --branch develop git@gitlab.com:$CI_PROJECT_PATH.git || true"
      - ssh $SSH_USR@$SSH_ADDR "cd $CI_PROJECT_NAME && chmod +x docker-clean.sh && ./docker-clean.sh || true"
      - ssh $SSH_USR@$SSH_ADDR "cd $CI_PROJECT_NAME && docker compose up -d --build --force-recreate"
    only:
      - develop

