stages:
#  - build
  - deploy


image: docker:20
services:
  - docker:20-dind

#build:
#  tags:
#    - build
#  stage: build
#  script:
#    - docker-compose build
#  only:
#    - develop


deploy:
  tags:
    - deploy
  stage: deploy
  script:
    - docker-compose up
  only:
    - develop

