  stages:
#    - build
#    - push
    - deploy

  variables:
    # Устанавливаем тэг для образа
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

#  build:
#    stage: build
#    services:
#      - docker:dind
#    image: docker:latest
#    script:
#      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#      - docker-compose build
#      - docker-compose push
#    only:
#      - develop

#  push:
#    stage: push
#    services:
#      - docker:dind
#    image: docker:latest
#    script:
#      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#      - docker-compose push
#    only:
#      - develop

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


  deploy:
    stage: deploy
    script:
      - ssh litvin_admin@95.163.229.202 "docker run --name postgres -p 5432:5432 -e POSTGRES_USER=username -e POSTGRES_PASSWORD=password -e POSTGRES_DB=postgres -d postgres:alpine"
      - ssh litvin_admin@95.163.229.202 "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
      - ssh litvin_admin@95.163.229.202 "docker pull $CI_REGISTRY_IMAGE/train2:$CI_COMMIT_REF_SLUG"
      - ssh litvin_admin@95.163.229.202 "docker stop train2 || true"
      - ssh litvin_admin@95.163.229.202 "docker rm train2 || true"
      - ssh litvin_admin@95.163.229.202 "docker run -d --name train2 -p 2226:2226 $CI_REGISTRY_IMAGE/train2:$CI_COMMIT_REF_SLUG"
    only:
      - develop
