stages:
  - build
  - deploy

image: docker:20
services:
  - docker:20-dind

build:
  stage: build
  script:
    - docker-compose build
    - docker-compose up
  only:
    - develop

deploy:
  stage: deploy
  script:
    - docker-compose up
  only:
    - develop

