  image:
    name: docker/compose:latest
    entrypoint: ['']

  stages:
    - build
    - deploy

  services:
    - docker:dind

  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""

  build:
    stage: build
#    tags:
#      - build
    script:
      - docker-compose pull
      - docker-compose build
    only:
      - develop

  deploy:
    stage: deploy
#    tags:
#      - deploy
    script:
      - docker-compose up -d
#      - docker-compose exec myservice my-test-script.sh
#    after_script:
#      - docker-compose down
    allow_failure: false
