stages:
  - build
  - deploy


variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:latest

services:
  - docker:dind


build:
  stage: build
  script:
    - docker-compose build
    - docker-compose up
  only:
    - develop

deploy:
  stage: deploy
  script:
    - docker-compose up
  only:
    - develop

