  stages:
#    - build
#    - push
    - deploy

  variables:
    # Устанавливаем тэг для образа
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

#  build:
#    stage: build
#    services:
#      - docker:dind
#    image: docker:latest
#    script:
#      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#      - docker-compose build
#      - docker-compose push
#    only:
#      - develop

#  push:
#    stage: push
#    services:
#      - docker:dind
#    image: docker:latest
#    script:
#      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#      - docker-compose push
#    only:
#      - develop

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'



  deploy:
    stage: deploy
    script:
      - ssh litvin_admin@95.163.229.202 "cd $CI_PROJECT_NAME && docker compose down"
      - ssh litvin_admin@95.163.229.202 "rm -rf $CI_PROJECT_NAME"
      - ssh litvin_admin@95.163.229.202 "git clone --depth 1 --branch develop git@gitlab.com:$CI_PROJECT_PATH.git"
      - ssh litvin_admin@95.163.229.202 "cd $CI_PROJECT_NAME && docker compose up -d"
    only:
      - develop
