stages:
  - build
  - deploy

image: gitlab/dind

services:
  - docker:dind

build:
  stage: build
  script:
    - docker-compose build
  only:
    - develop

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - develop
