stages:
  - build
#  - deploy
#variables:
#  DOCKER_HOST: tcp://docker:2375/
#  DOCKER_DRIVER: overlay2

# Official docker compose image.





before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  image:
    name: docker:cli
  services:
    - docker:dind
  tags:
    - build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up tester-image

#image: docker:20
#services:
#  - docker:20-dind

#build:
#  tags:
#    - build
#  stage: build
#  image: docker:20
#  services:
#    - docker:20-dind
#  script:
#    - docker-compose build
#  only:
#    - develop


#deploy:
#
#  stage: deploy
#  tags:
#    - deploy
#
#  script:
#    - docker-compose build
#    - docker-compose up -d
#  only:
#    - develop

