stages:
  - build
#  - deploy
#variables:
#  DOCKER_HOST: tcp://127.0.0.1:2375/
#  DOCKER_DRIVER: overlay2

# Official docker compose image.



#image:
#  name: docker:cli
#services:
#  - docker:dind

#before_script:
#  - docker version
#  - docker-compose version
image: gitlab/dind
services:
  - docker:dind
build:
  stage: build
  script:
    - docker-compose up -d
#    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
#    - docker build -t $CI_REGISTRY_IMAGE .
#    - docker push $CI_REGISTRY_IMAGE
#  tags:
#    - build
#  script:
#    - docker-compose down
#    - docker-compose build
#    - docker-compose up -d

#image: docker:20
#services:
#  - docker:20-dind

#build:
#  tags:
#    - build
#  stage: build
#  image: docker:20
#  services:
#    - docker:20-dind
#  script:
#    - docker-compose build
#  only:
#    - develop


#deploy:
#
#  stage: deploy
#  tags:
#    - deploy
#
#  script:
#    - docker-compose build
#    - docker-compose up -d
#  only:
#    - develop

