import io
import os
import time
from datetime import datetime
from zipfile import ZipFile
import pandas as pd
import sqlalchemy
from fastapi import APIRouter, Depends, UploadFile
from redis import Redis
from rq import Queue, get_current_job
from pydantic import BaseModel
from apps.train_api.src.upload_file import upload_files_new
from apps.train_api.src.utils import start_task, check_task_state
from pkg.auth import Authorization
from settings.db import sync_db, get_sync_session, conn_str
from settings.rd import get_redis_client

train_router = APIRouter(tags=["train"],
                         prefix="/api/v1/train",
                         responses=None)


# @train_router.get("/get_recommendations", status_code=200,
#                   dependencies=[Depends(Authorization(role='rw'))])

@train_router.post("/upload", status_code=200)
async def upload_data(file: UploadFile):
    """ Загрузка Zip файла """
    res, status = await check_task_state(job_id='upload_files')
    if status == "started":
        return {'result': res, 'state': status}

    contents = await file.read()
    bts = io.BytesIO(contents)
    res, ok = await start_task(f=upload_files_new, job_id='upload_files', conn_str=conn_str, bts=bts)
    return {'result': res, 'state': ok}


@train_router.get("/upload_state", status_code=200)
async def upload_state():
    """ Статус процесса"""
    res, status = await check_task_state(job_id='upload_files')
    return {'result': res, 'state': status}


s = {"forecasts": [
    {"date": "2024-06-14", "week": 24, "hours": [
    {"hour": "0", "icon": "ovc_ra", "temp": 16, "hour_ts": 1718312400, "prec_mm": 1.005, "humidity": 90, "uv_index": 0,
     "wind_dir": "n", "cloudness": 1, "condition": "rain", "prec_prob": 90, "prec_type": 1, "soil_temp": 0,
     "wind_gust": 9.3, "feels_like": 15, "is_thunder": null, "wind_speed": 400, "prec_period": 60, "pressure_mm": 744,
     "pressure_pa": 991, "prec_strength": 0.5, "soil_moisture": 0},
    {"hour": "1", "icon": "ovc_+ra", "temp": 16, "hour_ts": 1718316000, "prec_mm": 5.005, "humidity": 93, "uv_index": 0,
     "wind_dir": "n", "cloudness": 1, "condition": "heavy-rain", "prec_prob": 90, "prec_type": 1, "soil_temp": 0,
     "wind_gust": 9.6, "feels_like": 15, "is_thunder": null, "wind_speed": 400, "prec_period": 60, "pressure_mm": 744,
     "pressure_pa": 991, "prec_strength": 0.75, "soil_moisture": 0},
    {"hour": "2", "icon": "ovc_ra", "temp": 99, "hour_ts": 1718319600, "prec_mm": 1.005, "humidity": 92, "uv_index": 0,
     "wind_dir": "w", "cloudness": 1, "condition": "clear", "prec_prob": 90, "prec_type": 1, "soil_temp": 0,
     "wind_gust": 9.6, "feels_like": 15, "is_thunder": null, "wind_speed": 999, "prec_period": 60, "pressure_mm": 744,
     "pressure_pa": 991, "prec_strength": 0.5, "soil_moisture": 0},
    {"hour": "3", "icon": "ovc_ra", "temp": 15, "hour_ts": 1718323200, "prec_mm": 1.005, "humidity": 91, "uv_index": 0,
     "wind_dir": "nw", "cloudness": 1, "condition": "rain", "prec_prob": 90, "prec_type": 1, "soil_temp": 0,
     "wind_gust": 10.1, "feels_like": 13, "is_thunder": null, "wind_speed": 4, "prec_period": 60, "pressure_mm": 744,
     "pressure_pa": 991, "prec_strength": 0.5, "soil_moisture": 0},
    {"hour": "4", "icon": "ovc", "temp": 15, "hour_ts": 1718326800, "prec_mm": 0, "humidity": 89, "uv_index": 0,
     "wind_dir": "n", "cloudness": 1, "condition": "overcast", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 10, "feels_like": 13, "is_thunder": null, "wind_speed": 4.6, "prec_period": 60, "pressure_mm": 744,
     "pressure_pa": 991, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "5", "icon": "ovc", "temp": 15, "hour_ts": 1718330400, "prec_mm": 0, "humidity": 88, "uv_index": 0,
     "wind_dir": "n", "cloudness": 1, "condition": "overcast", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9.8, "feels_like": 13, "is_thunder": null, "wind_speed": 4.6, "prec_period": 60, "pressure_mm": 744,
     "pressure_pa": 991, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "6", "icon": "ovc", "temp": 15, "hour_ts": 1718334000, "prec_mm": 0, "humidity": 86, "uv_index": 0,
     "wind_dir": "n", "cloudness": 1, "condition": "overcast", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 10, "feels_like": 13, "is_thunder": null, "wind_speed": 4, "prec_period": 60, "pressure_mm": 744,
     "pressure_pa": 991, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "7", "icon": "bkn_d", "temp": 16, "hour_ts": 1718337600, "prec_mm": 0, "humidity": 83, "uv_index": 0,
     "wind_dir": "nw", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 10.1, "feels_like": 14, "is_thunder": null, "wind_speed": 4.5, "prec_period": 60, "pressure_mm": 745,
     "pressure_pa": 993, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "8", "icon": "bkn_d", "temp": 16, "hour_ts": 1718341200, "prec_mm": 0, "humidity": 76, "uv_index": 1,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 10.6, "feels_like": 13, "is_thunder": null, "wind_speed": 4.9, "prec_period": 60, "pressure_mm": 745,
     "pressure_pa": 993, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "9", "icon": "bkn_d", "temp": 17, "hour_ts": 1718344800, "prec_mm": 0, "humidity": 70, "uv_index": 2,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 10.6, "feels_like": 14, "is_thunder": null, "wind_speed": 4.5, "prec_period": 60, "pressure_mm": 745,
     "pressure_pa": 993, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "10", "icon": "bkn_-ra_d", "temp": 18, "hour_ts": 1718348400, "prec_mm": 0.105, "humidity": 65,
     "uv_index": 3, "wind_dir": "n", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 90, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 10.3, "feels_like": 15, "is_thunder": null, "wind_speed": 5, "prec_period": 60,
     "pressure_mm": 746, "pressure_pa": 994, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "11", "icon": "bkn_d", "temp": 19, "hour_ts": 1718352000, "prec_mm": 0, "humidity": 59, "uv_index": 5,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 10.1, "feels_like": 17, "is_thunder": null, "wind_speed": 4.6, "prec_period": 60, "pressure_mm": 746,
     "pressure_pa": 994, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "12", "icon": "bkn_d", "temp": 20, "hour_ts": 1718355600, "prec_mm": 0, "humidity": 56, "uv_index": 5,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9.3, "feels_like": 19, "is_thunder": null, "wind_speed": 3.7, "prec_period": 60, "pressure_mm": 746,
     "pressure_pa": 994, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "13", "icon": "bkn_d", "temp": 21, "hour_ts": 1718359200, "prec_mm": 0, "humidity": 53, "uv_index": 4,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9.3, "feels_like": 19, "is_thunder": null, "wind_speed": 3.9, "prec_period": 60, "pressure_mm": 746,
     "pressure_pa": 994, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "14", "icon": "bkn_d", "temp": 22, "hour_ts": 1718362800, "prec_mm": 0, "humidity": 51, "uv_index": 4,
     "wind_dir": "nw", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9, "feels_like": 21, "is_thunder": null, "wind_speed": 3.5, "prec_period": 60, "pressure_mm": 746,
     "pressure_pa": 994, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "15", "icon": "bkn_d", "temp": 22, "hour_ts": 1718366400, "prec_mm": 0, "humidity": 52, "uv_index": 3,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 8.3, "feels_like": 21, "is_thunder": null, "wind_speed": 2.5, "prec_period": 60, "pressure_mm": 746,
     "pressure_pa": 994, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "16", "icon": "bkn_d", "temp": 22, "hour_ts": 1718370000, "prec_mm": 0, "humidity": 51, "uv_index": 3,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 8.3, "feels_like": 21, "is_thunder": null, "wind_speed": 2.9, "prec_period": 60, "pressure_mm": 746,
     "pressure_pa": 994, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "17", "icon": "bkn_d", "temp": 22, "hour_ts": 1718373600, "prec_mm": 0, "humidity": 50, "uv_index": 2,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 8, "feels_like": 20, "is_thunder": null, "wind_speed": 2.7, "prec_period": 60, "pressure_mm": 746,
     "pressure_pa": 994, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "18", "icon": "bkn_d", "temp": 22, "hour_ts": 1718377200, "prec_mm": 0, "humidity": 49, "uv_index": 1,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 6.6, "feels_like": 21, "is_thunder": null, "wind_speed": 2.2, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "19", "icon": "bkn_d", "temp": 20, "hour_ts": 1718380800, "prec_mm": 0, "humidity": 52, "uv_index": 0,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 4.5, "feels_like": 19, "is_thunder": null, "wind_speed": 2, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "20", "icon": "bkn_d", "temp": 19, "hour_ts": 1718384400, "prec_mm": 0, "humidity": 57, "uv_index": 0,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2.7, "feels_like": 18, "is_thunder": null, "wind_speed": 1.7, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "21", "icon": "bkn_d", "temp": 18, "hour_ts": 1718388000, "prec_mm": 0, "humidity": 66, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2, "feels_like": 18, "is_thunder": null, "wind_speed": 1, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "22", "icon": "bkn_n", "temp": 18, "hour_ts": 1718391600, "prec_mm": 0, "humidity": 72, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.2, "feels_like": 18, "is_thunder": null, "wind_speed": 400, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "23", "icon": "bkn_n", "temp": 17, "hour_ts": 1718395200, "prec_mm": 0, "humidity": 75, "uv_index": 0,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.1, "feels_like": 17, "is_thunder": null, "wind_speed": 400, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0}],
     "parts": {
    "day": {"icon": "bkn_d", "polar": false, "_source": "12,13,14,15,16,17", "daytime": "d", "prec_mm": 0,
            "humidity": 52, "temp_avg": 22, "temp_max": 22, "temp_min": 20, "uv_index": 5, "wind_dir": "n",
            "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0, "wind_gust": 9.4,
            "feels_like": 21, "wind_speed": 3.9, "prec_period": 360, "pressure_mm": 746, "pressure_pa": 994,
            "fresh_snow_mm": 0, "prec_strength": 0, "soil_moisture": 0},
    "night": {"icon": "ovc_+ra", "polar": false, "_source": "0,1,2,3,4,5", "daytime": "n", "prec_mm": 8, "humidity": 91,
              "temp_avg": 16, "temp_max": 16, "temp_min": 15, "wind_dir": "n", "cloudness": 1,
              "condition": "heavy-rain", "prec_prob": 90, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.1,
              "feels_like": 14, "wind_speed": 4.7, "prec_period": 360, "pressure_mm": 744, "pressure_pa": 991,
              "fresh_snow_mm": 0, "prec_strength": 0.75, "soil_moisture": 0},
    "evening": {"icon": "bkn_d", "polar": false, "_source": "18,19,20,21", "daytime": "d", "prec_mm": 0, "humidity": 56,
                "temp_avg": 20, "temp_max": 22, "temp_min": 18, "uv_index": 1, "wind_dir": "n", "cloudness": 0.5,
                "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0, "wind_gust": 6.7,
                "feels_like": 19, "wind_speed": 2.2, "prec_period": 240, "pressure_mm": 747, "pressure_pa": 995,
                "fresh_snow_mm": 0, "prec_strength": 0, "soil_moisture": 0},
    "morning": {"icon": "bkn_-ra_d", "polar": false, "_source": "6,7,8,9,10,11", "daytime": "d", "prec_mm": 0.1,
                "humidity": 73, "temp_avg": 17, "temp_max": 19, "temp_min": 15, "uv_index": 3, "wind_dir": "n",
                "cloudness": 0.5, "condition": "light-rain", "prec_prob": 90, "prec_type": 1, "soil_temp": 0,
                "wind_gust": 10.7, "feels_like": 15, "wind_speed": 5, "prec_period": 360, "pressure_mm": 745,
                "pressure_pa": 993, "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "day_short": {"icon": "bkn_-ra_d", "temp": 22, "polar": false,
                  "_source": "6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21", "daytime": "d", "prec_mm": 0.1,
                  "humidity": 61, "temp_min": 15, "uv_index": 3, "wind_dir": "n", "cloudness": 0.5,
                  "condition": "light-rain", "prec_prob": 90, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.7,
                  "feels_like": 16, "wind_speed": 5, "prec_period": 960, "pressure_mm": 746, "pressure_pa": 994,
                  "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "night_short": {"icon": "ovc_+ra", "temp": 15, "polar": false, "_source": "0,1,2,3,4,5", "daytime": "n",
                    "prec_mm": 8, "humidity": 91, "wind_dir": "n", "cloudness": 1, "condition": "heavy-rain",
                    "prec_prob": 90, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.1, "feels_like": 14,
                    "wind_speed": 4.7, "prec_period": 360, "pressure_mm": 744, "pressure_pa": 991, "fresh_snow_mm": 0,
                    "prec_strength": 0.75, "soil_moisture": 0}},
                    "biomet": {"index": 0, "condition": "magnetic-field_0"}, "sunset": "21:14", "date_ts": 1718312400,
                    "set_end": "22:16", "sunrise": "03:43", "moon_code": 12, "moon_text": "moon-code-12",
                    "rise_begin": "02:43"},
    {"date": "2024-06-15", "week": 24, "hours": [
    {"hour": "0", "icon": "bkn_n", "temp": 1, "hour_ts": 1718398800, "prec_mm": 0, "humidity": 77, "uv_index": 0,
     "wind_dir": "w", "cloudness": 0.5, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 0.8, "feels_like": 16, "is_thunder": null, "wind_speed": 400, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "1", "icon": "bkn_n", "temp": 15, "hour_ts": 1718402400, "prec_mm": 0, "humidity": 78, "uv_index": 0,
     "wind_dir": "w", "cloudness": 0.5, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1, "feels_like": 15, "is_thunder": null, "wind_speed": 0.8, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "2", "icon": "bkn_n", "temp": 14, "hour_ts": 1718406000, "prec_mm": 0, "humidity": 80, "uv_index": 0,
     "wind_dir": "w", "cloudness": 0.5, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.8, "feels_like": 14, "is_thunder": null, "wind_speed": 0.8, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "3", "icon": "bkn_n", "temp": 14, "hour_ts": 1718409600, "prec_mm": 0, "humidity": 84, "uv_index": 0,
     "wind_dir": "w", "cloudness": 0.5, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.5, "feels_like": 14, "is_thunder": null, "wind_speed": 0.5, "prec_period": 60, "pressure_mm": 747,
     "pressure_pa": 995, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "4", "icon": "skc_d", "temp": 13, "hour_ts": 1718413200, "prec_mm": 0, "humidity": 84, "uv_index": 0,
     "wind_dir": "w", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.6, "feels_like": 13, "is_thunder": null, "wind_speed": 0.6, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "5", "icon": "skc_d", "temp": 14, "hour_ts": 1718416800, "prec_mm": 0, "humidity": 83, "uv_index": 0,
     "wind_dir": "s", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.7, "feels_like": 14, "is_thunder": null, "wind_speed": 0.6, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "6", "icon": "skc_d", "temp": 16, "hour_ts": 1718420400, "prec_mm": 0, "humidity": 78, "uv_index": 0,
     "wind_dir": "se", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.5, "feels_like": 16, "is_thunder": null, "wind_speed": 0.5, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "7", "icon": "skc_d", "temp": 19, "hour_ts": 1718424000, "prec_mm": 0, "humidity": 69, "uv_index": 1,
     "wind_dir": "e", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2, "feels_like": 19, "is_thunder": null, "wind_speed": 1, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "8", "icon": "skc_d", "temp": 21, "hour_ts": 1718427600, "prec_mm": 0, "humidity": 62, "uv_index": 2,
     "wind_dir": "s", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.2, "feels_like": 21, "is_thunder": null, "wind_speed": 1.2, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "9", "icon": "skc_d", "temp": 22, "hour_ts": 1718431200, "prec_mm": 0, "humidity": 52, "uv_index": 3,
     "wind_dir": "e", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.7, "feels_like": 22, "is_thunder": null, "wind_speed": 1.2, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "10", "icon": "bkn_d", "temp": 23, "hour_ts": 1718434800, "prec_mm": 0, "humidity": 48, "uv_index": 4,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2.9, "feels_like": 23, "is_thunder": null, "wind_speed": 1.7, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "11", "icon": "bkn_d", "temp": 23, "hour_ts": 1718438400, "prec_mm": 0, "humidity": 44, "uv_index": 5,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 3.9, "feels_like": 23, "is_thunder": null, "wind_speed": 1.8, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "12", "icon": "bkn_d", "temp": 24, "hour_ts": 1718442000, "prec_mm": 0, "humidity": 40, "uv_index": 5,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 3.5, "feels_like": 24, "is_thunder": null, "wind_speed": 1.7, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "13", "icon": "bkn_d", "temp": 24, "hour_ts": 1718445600, "prec_mm": 0, "humidity": 37, "uv_index": 5,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 3.7, "feels_like": 24, "is_thunder": null, "wind_speed": 2, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "14", "icon": "bkn_d", "temp": 24, "hour_ts": 1718449200, "prec_mm": 0, "humidity": 38, "uv_index": 5,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 4, "feels_like": 24, "is_thunder": null, "wind_speed": 2, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "15", "icon": "bkn_d", "temp": 25, "hour_ts": 1718452800, "prec_mm": 0, "humidity": 42, "uv_index": 2,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 3.7, "feels_like": 24, "is_thunder": null, "wind_speed": 1.7, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "16", "icon": "bkn_-ra_d", "temp": 25, "hour_ts": 1718456400, "prec_mm": 0.105, "humidity": 43,
     "uv_index": 1, "wind_dir": "e", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 4.8, "feels_like": 24, "is_thunder": null, "wind_speed": 2, "prec_period": 60,
     "pressure_mm": 748, "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "17", "icon": "bkn_-ra_d", "temp": 25, "hour_ts": 1718460000, "prec_mm": 0.105, "humidity": 43,
     "uv_index": 1, "wind_dir": "e", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 3.9, "feels_like": 24, "is_thunder": null, "wind_speed": 1.8, "prec_period": 60,
     "pressure_mm": 748, "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "18", "icon": "bkn_-ra_d", "temp": 24, "hour_ts": 1718463600, "prec_mm": 0.105, "humidity": 46,
     "uv_index": 1, "wind_dir": "ne", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 0, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 3, "feels_like": 23, "is_thunder": null, "wind_speed": 1.5, "prec_period": 60,
     "pressure_mm": 748, "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "19", "icon": "bkn_d", "temp": 24, "hour_ts": 1718467200, "prec_mm": 0, "humidity": 49, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 3, "feels_like": 24, "is_thunder": null, "wind_speed": 1.7, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "20", "icon": "bkn_d", "temp": 23, "hour_ts": 1718470800, "prec_mm": 0, "humidity": 55, "uv_index": 0,
     "wind_dir": "n", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 3.5, "feels_like": 23, "is_thunder": null, "wind_speed": 1.7, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "21", "icon": "bkn_-ra_d", "temp": 22, "hour_ts": 1718474400, "prec_mm": 0.105, "humidity": 62,
     "uv_index": 0, "wind_dir": "n", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 2.2, "feels_like": 22, "is_thunder": null, "wind_speed": 1.3, "prec_period": 60,
     "pressure_mm": 749, "pressure_pa": 998, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "22", "icon": "bkn_-ra_n", "temp": 20, "hour_ts": 1718478000, "prec_mm": 0.105, "humidity": 67,
     "uv_index": 0, "wind_dir": "ne", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 2, "feels_like": 20, "is_thunder": null, "wind_speed": 1.6, "prec_period": 60,
     "pressure_mm": 749, "pressure_pa": 998, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "23", "icon": "bkn_n", "temp": 20, "hour_ts": 1718481600, "prec_mm": 0, "humidity": 70, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2.5, "feels_like": 20, "is_thunder": null, "wind_speed": 1.5, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0}], "parts": {
    "day": {"icon": "bkn_-ra_d", "polar": false, "_source": "12,13,14,15,16,17", "daytime": "d", "prec_mm": 0.2,
            "humidity": 41, "temp_avg": 25, "temp_max": 25, "temp_min": 24, "uv_index": 3, "wind_dir": "e",
            "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0,
            "wind_gust": 4.8, "feels_like": 24, "wind_speed": 2, "prec_period": 360, "pressure_mm": 748,
            "pressure_pa": 997, "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "night": {"icon": "bkn_n", "polar": false, "_source": "22,23,0,1,2,3,4,5", "daytime": "n", "prec_mm": 0,
              "humidity": 79, "temp_avg": 15, "temp_max": 18, "temp_min": 13, "wind_dir": "e", "cloudness": 0.5,
              "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0, "wind_gust": 1.9, "feels_like": 15,
              "wind_speed": 0.9, "prec_period": 480, "pressure_mm": 747, "pressure_pa": 996, "fresh_snow_mm": 0,
              "prec_strength": 0, "soil_moisture": 0},
    "evening": {"icon": "bkn_-ra_d", "polar": false, "_source": "18,19,20,21", "daytime": "d", "prec_mm": 0.2,
                "humidity": 53, "temp_avg": 23, "temp_max": 24, "temp_min": 22, "uv_index": 1, "wind_dir": "ne",
                "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0,
                "wind_gust": 3.6, "feels_like": 23, "wind_speed": 1.8, "prec_period": 240, "pressure_mm": 748,
                "pressure_pa": 997, "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "morning": {"icon": "skc_d", "polar": false, "_source": "6,7,8,9,10,11", "daytime": "d", "prec_mm": 0,
                "humidity": 59, "temp_avg": 21, "temp_max": 23, "temp_min": 16, "uv_index": 5, "wind_dir": "e",
                "cloudness": 0.25, "condition": "partly-cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
                "wind_gust": 3.9, "feels_like": 22, "wind_speed": 1.9, "prec_period": 360, "pressure_mm": 748,
                "pressure_pa": 997, "fresh_snow_mm": 0, "prec_strength": 0, "soil_moisture": 0},
    "day_short": {"icon": "bkn_-ra_d", "temp": 25, "polar": false,
                  "_source": "6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21", "daytime": "d", "prec_mm": 0.4,
                  "humidity": 51, "temp_min": 16, "uv_index": 3, "wind_dir": "e", "cloudness": 0.5,
                  "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 4.8,
                  "feels_like": 23, "wind_speed": 2, "prec_period": 960, "pressure_mm": 748, "pressure_pa": 997,
                  "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "night_short": {"icon": "bkn_n", "temp": 13, "polar": false, "_source": "22,23,0,1,2,3,4,5", "daytime": "n",
                    "prec_mm": 0, "humidity": 79, "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy",
                    "prec_prob": 0, "prec_type": 0, "soil_temp": 0, "wind_gust": 1.9, "feels_like": 15,
                    "wind_speed": 0.9, "prec_period": 480, "pressure_mm": 747, "pressure_pa": 996, "fresh_snow_mm": 0,
                    "prec_strength": 0, "soil_moisture": 0}}, "biomet": {"index": 1, "condition": "magnetic-field_1"},
                                             "sunset": "21:15", "date_ts": 1718398800, "set_end": "22:16",
                                             "sunrise": "03:43", "moon_code": 12, "moon_text": "moon-code-12",
                                             "rise_begin": "02:43"}, {"date": "2024-06-16", "week": 24, "hours": [
    {"hour": "0", "icon": "bkn_n", "temp": 18, "hour_ts": 1718485200, "prec_mm": 0, "humidity": 72, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2.2, "feels_like": 18, "is_thunder": null, "wind_speed": 1.2, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "1", "icon": "bkn_n", "temp": 18, "hour_ts": 1718488800, "prec_mm": 0, "humidity": 74, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2.5, "feels_like": 18, "is_thunder": null, "wind_speed": 1.5, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "2", "icon": "skc_n", "temp": 17, "hour_ts": 1718492400, "prec_mm": 0, "humidity": 76, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2.4, "feels_like": 17, "is_thunder": null, "wind_speed": 1.3, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "3", "icon": "skc_n", "temp": 16, "hour_ts": 1718496000, "prec_mm": 0, "humidity": 79, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2, "feels_like": 16, "is_thunder": null, "wind_speed": 1.1, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "4", "icon": "skc_d", "temp": 16, "hour_ts": 1718499600, "prec_mm": 0, "humidity": 78, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2.4, "feels_like": 16, "is_thunder": null, "wind_speed": 1.3, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "5", "icon": "skc_d", "temp": 17, "hour_ts": 1718503200, "prec_mm": 0, "humidity": 76, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 1.5, "feels_like": 17, "is_thunder": null, "wind_speed": 1.5, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "6", "icon": "skc_d", "temp": 18, "hour_ts": 1718506800, "prec_mm": 0, "humidity": 75, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0, "condition": "clear", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 2.4, "feels_like": 18, "is_thunder": null, "wind_speed": 1.3, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "7", "icon": "bkn_d", "temp": 20, "hour_ts": 1718510400, "prec_mm": 0, "humidity": 67, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 4.9, "feels_like": 19, "is_thunder": null, "wind_speed": 2.4, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "8", "icon": "bkn_d", "temp": 22, "hour_ts": 1718514000, "prec_mm": 0, "humidity": 62, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 6.8, "feels_like": 22, "is_thunder": null, "wind_speed": 2.5, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "9", "icon": "bkn_d", "temp": 23, "hour_ts": 1718517600, "prec_mm": 0, "humidity": 58, "uv_index": 1,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 8.6, "feels_like": 23, "is_thunder": null, "wind_speed": 2.5, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "10", "icon": "bkn_d", "temp": 24, "hour_ts": 1718521200, "prec_mm": 0, "humidity": 52, "uv_index": 3,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9.3, "feels_like": 23, "is_thunder": null, "wind_speed": 3.7, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "11", "icon": "bkn_d", "temp": 24, "hour_ts": 1718524800, "prec_mm": 0, "humidity": 48, "uv_index": 5,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9.6, "feels_like": 23, "is_thunder": null, "wind_speed": 4, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "12", "icon": "bkn_d", "temp": 25, "hour_ts": 1718528400, "prec_mm": 0, "humidity": 44, "uv_index": 5,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9.6, "feels_like": 24, "is_thunder": null, "wind_speed": 3.9, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "13", "icon": "bkn_d", "temp": 26, "hour_ts": 1718532000, "prec_mm": 0, "humidity": 43, "uv_index": 4,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 10, "feels_like": 24, "is_thunder": null, "wind_speed": 4.4, "prec_period": 60, "pressure_mm": 750,
     "pressure_pa": 999, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "14", "icon": "bkn_d", "temp": 26, "hour_ts": 1718535600, "prec_mm": 0, "humidity": 42, "uv_index": 6,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9.8, "feels_like": 25, "is_thunder": null, "wind_speed": 4.5, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "15", "icon": "bkn_d", "temp": 26, "hour_ts": 1718539200, "prec_mm": 0, "humidity": 43, "uv_index": 4,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 9.6, "feels_like": 25, "is_thunder": null, "wind_speed": 3.7, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "16", "icon": "bkn_d", "temp": 26, "hour_ts": 1718542800, "prec_mm": 0, "humidity": 44, "uv_index": 3,
     "wind_dir": "e", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 10, "feels_like": 24, "is_thunder": null, "wind_speed": 4.5, "prec_period": 60, "pressure_mm": 749,
     "pressure_pa": 998, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "17", "icon": "bkn_-ra_d", "temp": 26, "hour_ts": 1718546400, "prec_mm": 0.105, "humidity": 43,
     "uv_index": 1, "wind_dir": "e", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 9.8, "feels_like": 24, "is_thunder": null, "wind_speed": 4.1, "prec_period": 60,
     "pressure_mm": 748, "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "18", "icon": "bkn_-ra_d", "temp": 25, "hour_ts": 1718550000, "prec_mm": 0.105, "humidity": 46,
     "uv_index": 1, "wind_dir": "e", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 9.5, "feels_like": 23, "is_thunder": null, "wind_speed": 3.7, "prec_period": 60,
     "pressure_mm": 748, "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "19", "icon": "bkn_-ra_d", "temp": 25, "hour_ts": 1718553600, "prec_mm": 0.105, "humidity": 47,
     "uv_index": 0, "wind_dir": "e", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 9, "feels_like": 23, "is_thunder": null, "wind_speed": 3.7, "prec_period": 60,
     "pressure_mm": 748, "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "20", "icon": "bkn_-ra_d", "temp": 24, "hour_ts": 1718557200, "prec_mm": 0.105, "humidity": 52,
     "uv_index": 0, "wind_dir": "e", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 8.6, "feels_like": 23, "is_thunder": null, "wind_speed": 3.2, "prec_period": 60,
     "pressure_mm": 748, "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "21", "icon": "bkn_-ra_d", "temp": 23, "hour_ts": 1718560800, "prec_mm": 0.105, "humidity": 56,
     "uv_index": 0, "wind_dir": "ne", "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1,
     "soil_temp": 0, "wind_gust": 8.1, "feels_like": 22, "is_thunder": null, "wind_speed": 2.7, "prec_period": 60,
     "pressure_mm": 748, "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
    {"hour": "22", "icon": "bkn_n", "temp": 22, "hour_ts": 1718564400, "prec_mm": 0, "humidity": 59, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 8.5, "feels_like": 21, "is_thunder": null, "wind_speed": 3.2, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0},
    {"hour": "23", "icon": "bkn_n", "temp": 21, "hour_ts": 1718568000, "prec_mm": 0, "humidity": 64, "uv_index": 0,
     "wind_dir": "ne", "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
     "wind_gust": 8.6, "feels_like": 20, "is_thunder": null, "wind_speed": 3.2, "prec_period": 60, "pressure_mm": 748,
     "pressure_pa": 997, "prec_strength": 0, "soil_moisture": 0}], "parts": {
    "day": {"icon": "bkn_-ra_d", "polar": false, "_source": "12,13,14,15,16,17", "daytime": "d", "prec_mm": 0.1,
            "humidity": 43, "temp_avg": 26, "temp_max": 26, "temp_min": 25, "uv_index": 3, "wind_dir": "e",
            "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0,
            "wind_gust": 10, "feels_like": 24, "wind_speed": 4.5, "prec_period": 360, "pressure_mm": 749,
            "pressure_pa": 998, "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "night": {"icon": "bkn_-ra_n", "polar": false, "_source": "22,23,0,1,2,3,4,5", "daytime": "n", "prec_mm": 0.1,
              "humidity": 74, "temp_avg": 18, "temp_max": 20, "temp_min": 16, "wind_dir": "ne", "cloudness": 0.25,
              "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 2.5,
              "feels_like": 18, "wind_speed": 1.6, "prec_period": 480, "pressure_mm": 749, "pressure_pa": 998,
              "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "evening": {"icon": "bkn_-ra_d", "polar": false, "_source": "18,19,20,21", "daytime": "d", "prec_mm": 0.4,
                "humidity": 50, "temp_avg": 24, "temp_max": 25, "temp_min": 23, "uv_index": 1, "wind_dir": "e",
                "cloudness": 0.5, "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0,
                "wind_gust": 9.5, "feels_like": 22, "wind_speed": 3.7, "prec_period": 240, "pressure_mm": 748,
                "pressure_pa": 997, "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "morning": {"icon": "bkn_d", "polar": false, "_source": "6,7,8,9,10,11", "daytime": "d", "prec_mm": 0,
                "humidity": 60, "temp_avg": 22, "temp_max": 24, "temp_min": 18, "uv_index": 5, "wind_dir": "e",
                "cloudness": 0.5, "condition": "cloudy", "prec_prob": 0, "prec_type": 0, "soil_temp": 0,
                "wind_gust": 9.6, "feels_like": 21, "wind_speed": 4.1, "prec_period": 360, "pressure_mm": 750,
                "pressure_pa": 999, "fresh_snow_mm": 0, "prec_strength": 0, "soil_moisture": 0},
    "day_short": {"icon": "bkn_-ra_d", "temp": 26, "polar": false,
                  "_source": "6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21", "daytime": "d", "prec_mm": 0.5,
                  "humidity": 51, "temp_min": 18, "uv_index": 3, "wind_dir": "e", "cloudness": 0.5,
                  "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 10,
                  "feels_like": 22, "wind_speed": 4.5, "prec_period": 960, "pressure_mm": 749, "pressure_pa": 998,
                  "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
    "night_short": {"icon": "bkn_-ra_n", "temp": 16, "polar": false, "_source": "22,23,0,1,2,3,4,5", "daytime": "n",
                    "prec_mm": 0.1, "humidity": 74, "wind_dir": "ne", "cloudness": 0.25, "condition": "light-rain",
                    "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 2.5, "feels_like": 18,
                    "wind_speed": 1.6, "prec_period": 480, "pressure_mm": 749, "pressure_pa": 998, "fresh_snow_mm": 0,
                    "prec_strength": 0.25, "soil_moisture": 0}}, "biomet": {"index": 1,
                                                                            "condition": "magnetic-field_1"},
                                                                      "sunset": "21:16", "date_ts": 1718485200,
                                                                      "set_end": "22:17", "sunrise": "03:43",
                                                                      "moon_code": 13, "moon_text": "moon-code-13",
                                                                      "rise_begin": "02:43"},
                   {"date": "2024-06-17", "week": 25, "hours": [
                       {"hour": "0", "icon": "ovc_-ra", "temp": 21, "hour_ts": 1718571600, "prec_mm": 0.2,
                        "humidity": 68, "uv_index": 0, "wind_dir": "ne", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 9, "feels_like": 21,
                        "is_thunder": null, "wind_speed": 2.7, "prec_period": 60, "pressure_mm": 748,
                        "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "1", "icon": "ovc_-ra", "temp": 20, "hour_ts": 1718575200, "prec_mm": 0.2,
                        "humidity": 71, "uv_index": 0, "wind_dir": "ne", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 9.3, "feels_like": 19,
                        "is_thunder": null, "wind_speed": 3.4, "prec_period": 60, "pressure_mm": 748,
                        "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "2", "icon": "ovc_-ra", "temp": 20, "hour_ts": 1718578800, "prec_mm": 0.2,
                        "humidity": 72, "uv_index": 0, "wind_dir": "ne", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 9.8, "feels_like": 19,
                        "is_thunder": null, "wind_speed": 3.5, "prec_period": 60, "pressure_mm": 748,
                        "pressure_pa": 997, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "3", "icon": "ovc_-ra", "temp": 20, "hour_ts": 1718582400, "prec_mm": 0.2,
                        "humidity": 75, "uv_index": 0, "wind_dir": "ne", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 9.6, "feels_like": 20,
                        "is_thunder": null, "wind_speed": 3.2, "prec_period": 60, "pressure_mm": 747,
                        "pressure_pa": 995, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "4", "icon": "ovc_-ra", "temp": 20, "hour_ts": 1718586000, "prec_mm": 0.5,
                        "humidity": 75, "uv_index": 0, "wind_dir": "ne", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 10, "feels_like": 19,
                        "is_thunder": null, "wind_speed": 3.7, "prec_period": 60, "pressure_mm": 747,
                        "pressure_pa": 995, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "5", "icon": "ovc_-ra", "temp": 19, "hour_ts": 1718589600, "prec_mm": 0.4,
                        "humidity": 77, "uv_index": 0, "wind_dir": "ne", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.1, "feels_like": 18,
                        "is_thunder": null, "wind_speed": 3.7, "prec_period": 60, "pressure_mm": 747,
                        "pressure_pa": 995, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "6", "icon": "ovc_-ra", "temp": 19, "hour_ts": 1718593200, "prec_mm": 0.3,
                        "humidity": 76, "uv_index": 0, "wind_dir": "ne", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 10, "feels_like": 18,
                        "is_thunder": null, "wind_speed": 3.5, "prec_period": 60, "pressure_mm": 747,
                        "pressure_pa": 995, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "7", "icon": "ovc_-ra", "temp": 19, "hour_ts": 1718596800, "prec_mm": 0.2,
                        "humidity": 77, "uv_index": 1, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.1, "feels_like": 18,
                        "is_thunder": null, "wind_speed": 4.3, "prec_period": 60, "pressure_mm": 747,
                        "pressure_pa": 995, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "8", "icon": "ovc_-ra", "temp": 20, "hour_ts": 1718600400, "prec_mm": 0.2,
                        "humidity": 76, "uv_index": 2, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.1, "feels_like": 19,
                        "is_thunder": null, "wind_speed": 4.5, "prec_period": 60, "pressure_mm": 746,
                        "pressure_pa": 994, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "9", "icon": "ovc_-ra", "temp": 20, "hour_ts": 1718604000, "prec_mm": 0.3,
                        "humidity": 74, "uv_index": 2, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.3, "feels_like": 19,
                        "is_thunder": null, "wind_speed": 400, "prec_period": 60, "pressure_mm": 746, "pressure_pa": 994,
                        "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "10", "icon": "ovc_-ra", "temp": 21, "hour_ts": 1718607600, "prec_mm": 0.3,
                        "humidity": 73, "uv_index": 3, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.3, "feels_like": 20,
                        "is_thunder": null, "wind_speed": 4.6, "prec_period": 60, "pressure_mm": 746,
                        "pressure_pa": 994, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "11", "icon": "ovc_-ra", "temp": 21, "hour_ts": 1718611200, "prec_mm": 0.3,
                        "humidity": 72, "uv_index": 3, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.3, "feels_like": 20,
                        "is_thunder": null, "wind_speed": 4.6, "prec_period": 60, "pressure_mm": 746,
                        "pressure_pa": 994, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "12", "icon": "ovc_-ra", "temp": 22, "hour_ts": 1718614800, "prec_mm": 0.4,
                        "humidity": 73, "uv_index": 3, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.1, "feels_like": 22,
                        "is_thunder": null, "wind_speed": 4.1, "prec_period": 60, "pressure_mm": 746,
                        "pressure_pa": 994, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "13", "icon": "ovc_-ra", "temp": 22, "hour_ts": 1718618400, "prec_mm": 0.4,
                        "humidity": 72, "uv_index": 1, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.3, "feels_like": 21,
                        "is_thunder": null, "wind_speed": 4.5, "prec_period": 60, "pressure_mm": 745,
                        "pressure_pa": 993, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "14", "icon": "ovc_-ra", "temp": 23, "hour_ts": 1718622000, "prec_mm": 0.4,
                        "humidity": 70, "uv_index": 1, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.6, "feels_like": 23,
                        "is_thunder": null, "wind_speed": 4.1, "prec_period": 60, "pressure_mm": 745,
                        "pressure_pa": 993, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "15", "icon": "ovc_-ra", "temp": 23, "hour_ts": 1718625600, "prec_mm": 0.995,
                        "humidity": 74, "uv_index": 1, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 11.1, "feels_like": 23,
                        "is_thunder": null, "wind_speed": 3.9, "prec_period": 60, "pressure_mm": 745,
                        "pressure_pa": 993, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "16", "icon": "ovc_-ra", "temp": 23, "hour_ts": 1718629200, "prec_mm": 0.4,
                        "humidity": 74, "uv_index": 1, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 11.3, "feels_like": 23,
                        "is_thunder": null, "wind_speed": 4.4, "prec_period": 60, "pressure_mm": 745,
                        "pressure_pa": 993, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "17", "icon": "ovc_-ra", "temp": 23, "hour_ts": 1718632800, "prec_mm": 0.5,
                        "humidity": 74, "uv_index": 0, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 12.1, "feels_like": 23,
                        "is_thunder": null, "wind_speed": 4.5, "prec_period": 60, "pressure_mm": 745,
                        "pressure_pa": 993, "prec_strength": 0.25, "soil_moisture": 0},
                       {"hour": "18", "icon": "ovc_-ra", "temp": 23, "hour_ts": 1718636400, "prec_mm": 0.4,
                        "humidity": 82, "uv_index": 0, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                        "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 11.3, "feels_like": 24,
                        "is_thunder": null, "wind_speed": 3.7, "prec_period": 60, "pressure_mm": 744,
                        "pressure_pa": 991, "prec_strength": 0.25, "soil_moisture": 0}], "parts": {
                       "day": {"icon": "ovc_-ra", "polar": false, "_source": "12,13,14,15,16,17", "daytime": "d",
                               "prec_mm": 3, "humidity": 73, "temp_avg": 23, "temp_max": 23, "temp_min": 22,
                               "uv_index": 3, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                               "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 12.2, "feels_like": 23,
                               "wind_speed": 4.5, "prec_period": 360, "pressure_mm": 745, "pressure_pa": 993,
                               "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
                       "night": {"icon": "ovc_-ra", "polar": false, "_source": "22,23,0,1,2,3,4,5", "daytime": "n",
                                 "prec_mm": 1.7, "humidity": 70, "temp_avg": 20, "temp_max": 22, "temp_min": 19,
                                 "wind_dir": "ne", "cloudness": 1, "condition": "light-rain", "prec_prob": 20,
                                 "prec_type": 1, "soil_temp": 0, "wind_gust": 10.1, "feels_like": 19, "wind_speed": 3.8,
                                 "prec_period": 480, "pressure_mm": 748, "pressure_pa": 996, "fresh_snow_mm": 0,
                                 "prec_strength": 0.25, "soil_moisture": 0},
                       "evening": {"icon": "ovc_-ra", "polar": false, "_source": "18,21", "daytime": "d",
                                   "prec_mm": 1.1, "humidity": 84, "temp_avg": 22, "temp_max": 23, "temp_min": 21,
                                   "wind_dir": "e", "cloudness": 1, "condition": "light-rain", "prec_prob": 20,
                                   "prec_type": 1, "soil_temp": 0, "wind_gust": 11.3, "feels_like": 23,
                                   "wind_speed": 3.8, "prec_period": 240, "pressure_mm": 744, "pressure_pa": 991,
                                   "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
                       "morning": {"icon": "ovc_-ra", "polar": false, "_source": "6,7,8,9,10,11", "daytime": "d",
                                   "prec_mm": 1.5, "humidity": 75, "temp_avg": 20, "temp_max": 21, "temp_min": 19,
                                   "uv_index": 3, "wind_dir": "e", "cloudness": 1, "condition": "light-rain",
                                   "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 10.3, "feels_like": 19,
                                   "wind_speed": 4.7, "prec_period": 360, "pressure_mm": 746, "pressure_pa": 994,
                                   "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
                       "day_short": {"icon": "ovc_-ra", "temp": 23, "polar": false,
                                     "_source": "6,7,8,9,10,11,12,13,14,15,16,17,18,21", "daytime": "d", "prec_mm": 5.7,
                                     "humidity": 75, "temp_min": 19, "uv_index": 3, "wind_dir": "e", "cloudness": 1,
                                     "condition": "light-rain", "prec_prob": 30, "prec_type": 1, "soil_temp": 0,
                                     "wind_gust": 12.2, "feels_like": 20, "wind_speed": 4.7, "prec_period": 960,
                                     "pressure_mm": 746, "pressure_pa": 993, "fresh_snow_mm": 0, "prec_strength": 0.25,
                                     "soil_moisture": 0},
                       "night_short": {"icon": "ovc_-ra", "temp": 19, "polar": false, "_source": "22,23,0,1,2,3,4,5",
                                       "daytime": "n", "prec_mm": 1.7, "humidity": 70, "wind_dir": "ne", "cloudness": 1,
                                       "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0,
                                       "wind_gust": 10.1, "feels_like": 19, "wind_speed": 3.8, "prec_period": 480,
                                       "pressure_mm": 748, "pressure_pa": 996, "fresh_snow_mm": 0,
                                       "prec_strength": 0.25, "soil_moisture": 0}},
                    "biomet": {"index": 0, "condition": "magnetic-field_0"}, "sunset": "21:16", "date_ts": 1718571600,
                    "set_end": "22:18", "sunrise": "03:43", "moon_code": 13, "moon_text": "moon-code-13",
                    "rise_begin": "02:42"}, {"date": "2024-06-18", "week": 25, "hours": [], "parts": {
        "day": {"icon": "ovc_-ra", "polar": false, "_source": "12,15", "daytime": "d", "prec_mm": 0.7, "humidity": 76,
                "temp_avg": 23, "temp_max": 23, "temp_min": 22, "uv_index": 3, "wind_dir": "sw", "cloudness": 1,
                "condition": "light-rain", "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 8.5,
                "feels_like": 24, "wind_speed": 3.4, "prec_period": 360, "pressure_mm": 743, "pressure_pa": 990,
                "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
        "night": {"icon": "ovc_-ra", "polar": false, "_source": "0,3", "daytime": "n", "prec_mm": 0.4, "humidity": 91,
                  "temp_avg": 19, "temp_max": 19, "temp_min": 19, "wind_dir": "e", "cloudness": 1,
                  "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 5.9,
                  "feels_like": 20, "wind_speed": 2.5, "prec_period": 360, "pressure_mm": 744, "pressure_pa": 991,
                  "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
        "evening": {"icon": "ovc_-ra", "polar": false, "_source": "18,21", "daytime": "d", "prec_mm": 0.5,
                    "humidity": 82, "temp_avg": 20, "temp_max": 21, "temp_min": 19, "wind_dir": "w", "cloudness": 1,
                    "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 9,
                    "feels_like": 20, "wind_speed": 3.3, "prec_period": 360, "pressure_mm": 744, "pressure_pa": 991,
                    "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
        "morning": {"icon": "ovc_-ra", "polar": false, "_source": "6,9", "daytime": "d", "prec_mm": 0.6, "humidity": 85,
                    "temp_avg": 20, "temp_max": 21, "temp_min": 19, "uv_index": 3, "wind_dir": "se", "cloudness": 1,
                    "condition": "light-rain", "prec_prob": 20, "prec_type": 1, "soil_temp": 0, "wind_gust": 8.2,
                    "feels_like": 21, "wind_speed": 3.3, "prec_period": 360, "pressure_mm": 743, "pressure_pa": 990,
                    "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
        "day_short": {"icon": "ovc_-ra", "temp": 23, "polar": false, "_source": "6,9,12,15,18,21", "daytime": "d",
                      "prec_mm": 1.8, "humidity": 81, "temp_min": 19, "uv_index": 3, "wind_dir": "w", "cloudness": 1,
                      "condition": "light-rain", "prec_prob": 30, "prec_type": 1, "soil_temp": 0, "wind_gust": 9,
                      "feels_like": 22, "wind_speed": 3.4, "prec_period": 1080, "pressure_mm": 743, "pressure_pa": 990,
                      "fresh_snow_mm": 0, "prec_strength": 0.25, "soil_moisture": 0},
        "night_short": {"icon": "ovc_-ra", "temp": 19, "polar": false, "_source": "0,3", "daytime": "n", "prec_mm": 0.4,
                        "humidity": 91, "wind_dir": "e", "cloudness": 1, "condition": "light-rain", "prec_prob": 20,
                        "prec_type": 1, "soil_temp": 0, "wind_gust": 5.9, "feels_like": 20, "wind_speed": 2.5,
                        "prec_period": 360, "pressure_mm": 744, "pressure_pa": 991, "fresh_snow_mm": 0,
                        "prec_strength": 0.25, "soil_moisture": 0}}, "biomet": {"index": 0, "condition": ""},
                                             "sunset": "21:17", "date_ts": 1718658000, "set_end": "22:18",
                                             "sunrise": "03:43", "moon_code": 14, "moon_text": "moon-code-14",
                                             "rise_begin": "02:42"}]}
